"""Generate static site pages from a shared shell; no private data embedded."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1] / 'web'

def page(name, title, content):
    html = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="STRATEVO evidence-led sourcing and supplier applications. Private research, human review, clear next steps."><title>'''+title+''' | STRATEVO</title><link rel="stylesheet" href="/site.css"><script defer src="/site.js"></script></head><body><header><a class="brand" href="/">STRATEVO<span>EVIDENCE-LED SOURCING</span></a><nav aria-label="Main navigation"><a href="/ai">Intelligence</a><a href="/supplier">For suppliers</a><a href="/supplier#sign-in">Supplier access</a></nav><a class="booking" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Book a call ↗</a></header><main class="site-main">'''+content+'''<footer class="footer-nav"><span>STRATEVO / Research. Review. Human judgment.<br>No AI orders, payments or contracts. Paid sourcing requires a separate signed proposal.</span><span><a href="mailto:hello@stratevo.co">hello@stratevo.co</a> · <a href="/supplier#privacy">Application privacy</a> · <a href="/admin">Manager access</a></span></footer></main></body></html>'''
    (ROOT/name).write_text(html)

page('home.html','Evidence-led sourcing', '''
<section class="hero"><div><div class="eyebrow">INDEPENDENT B2B SOURCING PARTNER</div><h1>Find the right fit.<br><span>Not just a supplier.</span></h1><p class="intro">Move from product questions to a clearer sourcing brief. Explore research, understand the unknowns, and put human review before commitments.</p><div class="actions"><a class="primary" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Discuss your sourcing needs ↗</a><a class="secondary" href="/supplier">Join as a supplier</a></div><p class="sub">Approval-only platform. No instant purchasing. No unsupported promises.</p></div><div class="signal" aria-hidden="true"><div class="orbit"></div><div class="orbit"></div><div class="orbit"></div><div class="signal-center"><strong>S</strong>STRATEVO</div><span class="signal-label">RESEARCH → REVIEW → CLARITY</span></div></section>
<div class="trust-line"><span>01 / PRIVATE SOURCE RESEARCH</span><span>02 / MANUAL APPLICATION REVIEW</span><span>03 / CLEAR HUMAN HANDOFF</span></div>
<section class="section" id="brief"><div class="eyebrow">THE BRIEF</div><h2>You bring the requirement.<br>We build the route to supply.</h2><p class="section-intro">From an early idea to a complete RFQ, we clarify your specifications and work toward a qualified, commercially sound route to supply. Evidence and human judgment come before commitments.</p><ol class="process-line" aria-label="Sourcing stages"><li>Source</li><li>Qualify</li><li>Compare</li><li>Negotiate</li><li>Deliver</li></ol></section>
<section class="section"><div class="eyebrow">FOUR SOURCING PILLARS</div><h2>Focused on your requirement.</h2><div class="pillar-grid"><article class="feature"><h3>Industrial components</h3><p>Technical specifications, tolerances and manufacturing capability.</p></article><article class="feature"><h3>Packaging</h3><p>Materials, dimensions, print requirements and intended use.</p></article><article class="feature"><h3>Consumer products</h3><p>Product variants, quality standards and destination-market requirements.</p></article><article class="feature"><h3>Food &amp; ingredients</h3><p>Composition, traceability and required safety documentation.</p></article></div><p class="sub">Service scope—not a claim of verified suppliers in every category.</p></section>
<section class="section"><div class="eyebrow">FROM DEFINITION TO DELIVERY</div><h2>A clear next step at every stage.</h2><ol class="customer-stages"><li><strong>Definition Call</strong><p>Confirm product, volume, preferred supplier location and certifications, then timing and target cost.</p></li><li><strong>Supplier Identification</strong><p>Review available research; verify identity, capability and evidence before recommendation.</p></li><li><strong>Negotiation</strong><p>Compare commercial terms, MOQ, tooling, logistics and delivery risk under an agreed scope.</p></li><li><strong>Delivery &amp; Support</strong><p>Agree the onboarding and follow-through needed for the engagement. No AI order acceptance.</p></li></ol></section>
<section class="section"><div class="eyebrow">A MORE CONSIDERED PROCESS</div><h2>Evidence before introductions.</h2><p class="section-intro">A listing is a starting point, not proof. We keep advertised claims separate from confirmed facts, so the next conversation starts with better questions.</p><div class="three"><article class="feature"><span class="number">01 — DEFINE</span><h3>Start with the brief.</h3><p>Product, specification, quantity, destination and timing. Make the requirements clear before comparing possibilities.</p></article><article class="feature"><span class="number">02 — INVESTIGATE</span><h3>Look beyond the listing.</h3><p>Review available research and identify gaps in pricing, variants, documentation and manufacturing capability.</p></article><article class="feature"><span class="number">03 — REVIEW</span><h3>Keep people in control.</h3><p>Supplier applications require a manager decision. Commercial sourcing proceeds only under a separate agreed proposal.</p></article></div></section>
<section class="bottom-cta"><div><div class="eyebrow">FOR MANUFACTURERS & SUPPLIERS</div><h2>Bring your capabilities into focus.</h2><p>Submit your business details and license for private review.<br>Review target: 1–3 business days after email verification.</p></div><a class="primary" href="/supplier">Apply to join ↗</a></section>
<section class="section"><div class="eyebrow">SOURCING INTELLIGENCE</div><h2>A clearer starting point.</h2><p class="section-intro">The owner research workspace supports catalog search and an optional conversational AI connection. Research remains unverified until checked; access is currently restricted to the owner.</p><a class="secondary" href="/ai">Open intelligence workspace ↗</a></section>
''')
page('supplier.html','Supplier applications', '''
<div class="page-top"><div class="eyebrow">SUPPLIER NETWORK / APPLICATIONS</div><h1>Your next opportunity<br><span>starts with a review.</span></h1><p class="intro">Tell us about your business and capabilities. Applications are private and reviewed manually—not automatically approved.</p></div>
<div class="application-layout"><section class="form-panel"><h2>Business application</h2><p class="sub">All fields required unless marked optional.</p><form id="application-form"><div class="form-grid">
<div class="field"><label for="company">Registered company name</label><input id="company" name="company" maxlength="200" autocomplete="organization" required></div>
<div class="field"><label for="contact">Contact person</label><input id="contact" name="contact" maxlength="200" autocomplete="name" required></div>
<div class="field"><label for="email">Business email</label><input id="email" name="email" type="email" maxlength="254" autocomplete="email" required></div>
<div class="field"><label for="country">Country / region of registration</label><input id="country" name="country" maxlength="100" autocomplete="country-name" required></div>
<div class="field full"><label for="category">Main product category</label><input id="category" name="category" placeholder="e.g. Lighting and seasonal decorations" maxlength="150" required></div>
<div class="field"><label for="whatsapp">WhatsApp (optional if WeChat provided)</label><input id="whatsapp" name="whatsapp" type="tel" maxlength="60" placeholder="Include country code"></div>
<div class="field"><label for="wechat">WeChat (optional if WhatsApp provided)</label><input id="wechat" name="wechat" maxlength="100" placeholder="Your WeChat ID"></div>
<div class="field full"><label for="capabilities">Products and capabilities</label><textarea id="capabilities" name="capabilities" rows="5" minlength="20" maxlength="4000" placeholder="Products, manufacturing or trading role, typical MOQs, capacity and export experience. Label claims that still need supporting evidence." required></textarea></div>
<div class="field"><label for="license_number">Business registration / license number</label><input id="license_number" name="license_number" maxlength="150" required></div>
<div class="field"><label for="license-file">Business license PDF</label><input id="license-file" type="file" accept="application/pdf,.pdf" required><small>PDF only, maximum 2 MB. Private manager access. Redact unrelated personal identifiers before uploading.</small></div></div>
<label class="check"><input name="consent" type="checkbox" required><span>I confirm I am authorized to submit these details and have read the <a href="#privacy">application privacy notice</a>. I understand that applying does not grant access or constitute certification.</span></label><button type="submit">Submit for email verification ↗</button><p id="application-status" class="form-status" role="status"></p></form></section>
<aside><section class="aside-block"><h2>What happens next</h2><ol class="steps"><li><strong>01 / Verify your email</strong>Use the secure link sent to your business email.</li><li><strong>02 / Manager review</strong>Your business details and license are reviewed. Target: 1–3 business days, not a guarantee.</li><li><strong>03 / Receive a decision</strong>Approved applicants receive a single-use access link. Rejected applicants receive a decision email.</li></ol></section>
<section class="aside-block" id="sign-in"><h2>Already applied?</h2><p>Request a new verification link or, if approved, a sign-in link. Pending and rejected applications cannot access the platform.</p><form id="access-form"><label class="sr" for="access-email">Application email</label><input id="access-email" name="email" type="email" maxlength="254" placeholder="Your application email" required><button type="submit">Email me a secure link</button><p id="access-status" class="form-status" role="status"></p></form></section>
<section id="privacy" class="aside-block"><h2>Application privacy</h2><ul class="privacy-list"><li>Business details, contact channels and your license are collected for application review and account access.</li><li>They are not published in the public catalog or sent to the conversational AI.</li><li>Authorized managers can view your application and download the license. Email delivery requires an external mail provider.</li><li>Approval is platform access only—not a certification, purchase commitment or contract.</li><li>This development site is not yet connected to production email. Do not submit real sensitive documents until the operator’s production privacy and retention terms are provided.</li></ul></section></aside></div>
''')
page('admin.html','Application manager', '''
<div class="page-top"><div class="eyebrow">PRIVATE / MANAGER WORKSPACE</div><h1>Supplier review.<br><span>Every decision, deliberate.</span></h1><p class="intro">Review business details, check supporting documents, and control access to the platform.</p></div>
<section id="admin-login" class="form-panel narrow"><h2>Manager sign-in</h2><p class="sub">Use your configured manager password. Research workspace tokens do not grant manager access.</p><form id="admin-login-form"><div class="field"><label for="admin-password">Manager password</label><input id="admin-password" name="password" type="password" autocomplete="current-password" maxlength="300" required></div><div class="actions"><button type="submit">Sign in securely</button></div><p id="admin-login-status" class="form-status" role="status"></p></form></section>
<section id="admin-workspace" hidden><section class="form-panel"><h2>Service connections</h2><p class="sub">Add credentials in your hosting project’s server environment variables, then redeploy. Never enter keys in chat or frontend code. AI: AI_API_KEY, AI_MODEL, AI_BASE_URL. Online search: BRAVE_SEARCH_API_KEY and ONLINE_DISCOVERY_ENABLED=true.</p><p id="connection-status" role="status"></p><div class="actions"><button type="button" id="check-ai" class="quiet">Test AI connection</button><button type="button" id="check-search" class="quiet">Test online search</button></div><p class="sub">Tests call the configured providers and may incur charges. Search tests use the daily search budget. Email delivery still requires SMTP and a mail worker.</p><p id="connection-test-status" role="status"></p></section><div class="panel-title"><h2>Application queue</h2><button class="quiet" id="admin-logout">Sign out</button></div><p id="admin-summary" class="admin-summary"></p><div class="notice">Approval grants supplier account access only. Check the license and claimed capabilities independently. Uploaded PDFs are not malware-scanned; handle downloads in a secure document viewer.</div><div class="toolbar"><label class="sr" for="filter-search">Search applications</label><input id="filter-search" placeholder="Search company, email or category"><label class="sr" for="filter-status">Application status</label><select id="filter-status"><option value="pending">Awaiting review</option><option value="all">All applications</option><option value="pending_email">Email unverified</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button id="refresh" class="quiet">Refresh</button><button id="send-mail" class="quiet">Send next queued email</button></div><p id="admin-status" class="form-status" role="status"></p><div id="applications"></div><section class="section"><div class="eyebrow">SEPARATE FROM PLATFORM MEMBERSHIP</div><h2>Private supplier research</h2><p class="section-intro">Owner-provided listing summaries are research leads—not approved or verified supplier accounts. Names shown here are manager-only and are not sent to the AI.</p><div class="actions"><button class="quiet" id="load-research">Load private research</button><a class="secondary" href="/ai">Open AI workspace ↗</a></div><p id="research-status" class="form-status" role="status"></p><div id="research-records"></div></section></section>
''')
page('access.html','Secure email access', '''
<section class="narrow"><div class="eyebrow">SINGLE-USE / EMAIL ACCESS</div><h1>One secure link.<br><span>Your next step.</span></h1><div class="form-panel"><h2>Continue with your email link</h2><p class="sub">Confirm below to verify your application email or sign in to an approved account. Links expire and can only be used once.</p><button id="consume-link">Continue securely</button><p id="consume-status" class="form-status" role="status"></p><a id="portal-link" class="primary" href="/portal" hidden>Open supplier account ↗</a><p class="sub"><a href="/supplier#sign-in">Request a new link</a></p></div></section>
''')
page('portal.html','Supplier account', '''
<div class="page-top"><div class="eyebrow">APPROVED SUPPLIER / ACCOUNT</div><h1>Welcome to<br><span>your supplier account.</span></h1><p class="intro">Your application has been approved for platform access. Commercial activity remains subject to a separate agreement.</p></div><p id="portal-status" class="form-status" role="status"></p><div id="portal-content" hidden><div class="portal-grid"><section class="form-panel"><div class="panel-title"><h2>Business profile</h2><span class="badge approved">Approved access</span></div><dl id="profile" class="details"></dl></section><section class="form-panel"><h2>Next steps</h2><p class="intro">Discuss your capabilities and relevant sourcing requirements with the STRATEVO team.</p><a class="primary" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Arrange a conversation ↗</a><p class="notice">No orders, payments, certification badges or public supplier introductions are created by approval.</p></section></div><div class="actions"><button id="supplier-logout" class="quiet">Sign out</button></div></div>
''')
