"""Generate static site pages from a shared shell; no private data embedded."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1] / 'web'

LOGO = '<svg viewBox="0 0 34 32" aria-hidden="true"><path d="M32 2H13C3 2 0 11 8 16L22 24H5L1 31H21C32 31 35 22 26 16L13 9H28Z"/></svg>'

def page(name, title, content):
    home = name == 'home.html'
    body_class = 'reference-home' if home else 'reference-inner'
    html = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="STRATEVO independent B2B sourcing. Clear requirements, private research and human review."><title>'+title+' | STRATEVO</title><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/reference.css"><script defer src="/site.js"></script><script defer src="/visual.js"></script></head><body class="'+body_class+'">'
    html += '<a class="skip-link" href="#main-content">Skip to content</a><canvas id="constellation" aria-hidden="true"></canvas><div class="site-chrome"><div class="preview-strip"><strong>NON-CONTRACTING PREVIEW</strong><span>Supplier applications may be reviewed, but no orders or payments are accepted. Operator disclosure is pending.</span><a href="/#launch-status">Launch status</a><a href="/admin">Manager access</a></div><header class="reference-header"><a class="brand" href="/" aria-label="STRATEVO home">'+LOGO+'<span>STRATEVO</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" type="button">Menu <span aria-hidden="true">+</span></button><nav id="main-nav" aria-label="Main navigation"><a href="/ai">STRATEVO AI</a><a href="/#coverage">Marketplace</a><a href="/#process">The process</a><a href="/#network">Network</a><a class="mobile-nav-link" href="/supplier">Are you a supplier?</a><a class="mobile-nav-link" href="/supplier#sign-in">Supplier access</a><a class="mobile-nav-link" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Book a sourcing review ↗</a></nav><div class="header-actions"><a class="supplier-link" href="/supplier">Are you a supplier?</a><a class="rfq-link" href="/ai#match-form">Start an RFQ</a><a class="booking" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Book a sourcing review <span aria-hidden="true">↗</span></a></div></header></div><main class="site-main" id="main-content">'
    html += content
    html += '<footer class="footer-nav"><a class="brand" href="/">'+LOGO+'<span>STRATEVO</span></a><span>Independent B2B sourcing.<br>Research. Evidence. Human judgment.</span><span><a href="mailto:hello@stratevo.co">hello@stratevo.co</a><br><a href="/supplier#privacy">Application privacy</a> · <a href="/admin">Manager access</a></span></footer></main>'
    if home:
        html += '<a class="floating-ai" href="/ai"><i aria-hidden="true"></i><span aria-hidden="true">✧</span> Ask STRATEVO</a>'
    if name == 'index.html':
        html += '<script defer src="/app.js"></script>'
    html += '</body></html>'
    (ROOT/name).write_text(html)

page('home.html','Independent B2B sourcing', (ROOT/'templates'/'home.content.html').read_text())
page('supplier.html','Supplier applications', (ROOT/'templates'/'supplier.content.html').read_text())
page('admin.html','Application manager', '''
<div class="page-top"><div class="eyebrow">PRIVATE / MANAGER WORKSPACE</div><h1>Supplier review.<br><span>Every decision, deliberate.</span></h1><p class="intro">Review business details, check supporting documents, and control access to the platform.</p></div>
<section id="admin-login" class="form-panel narrow"><h2>Manager sign-in</h2><p class="sub">Use your configured manager password. Research workspace tokens do not grant manager access.</p><form id="admin-login-form"><div class="field"><label for="admin-password">Manager password</label><input id="admin-password" name="password" type="password" autocomplete="current-password" maxlength="300" required></div><div class="actions"><button type="submit">Sign in securely</button></div><p id="admin-login-status" class="form-status" role="status"></p></form></section>
<section id="admin-workspace" hidden><section class="form-panel"><h2>Service connections</h2><p class="sub">Add credentials in your hosting project’s server environment variables, then redeploy. Never enter keys in chat or frontend code. AI: AI_API_KEY, AI_MODEL, AI_BASE_URL. Online search: BRAVE_SEARCH_API_KEY and ONLINE_DISCOVERY_ENABLED=true.</p><p id="connection-status" role="status"></p><div class="actions"><button type="button" id="check-ai" class="quiet">Test AI connection</button><button type="button" id="check-search" class="quiet">Test online search</button></div><p class="sub">Tests call the configured providers and may incur charges. Search tests use the daily search budget. Email delivery still requires SMTP and a mail worker.</p><p id="connection-test-status" role="status"></p></section><div class="panel-title"><h2>Application queue</h2><button class="quiet" id="admin-logout">Sign out</button></div><p id="admin-summary" class="admin-summary"></p><div class="notice">Approval grants supplier account access only. Check the license and claimed capabilities independently. Uploaded PDFs are not malware-scanned; handle downloads in a secure document viewer.</div><div class="toolbar"><label class="sr" for="filter-search">Search applications</label><input id="filter-search" placeholder="Search company, email or category"><label class="sr" for="filter-status">Application status</label><select id="filter-status"><option value="pending">Awaiting review</option><option value="all">All applications</option><option value="pending_email">Email unverified</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button id="refresh" class="quiet">Refresh</button><button id="send-mail" class="quiet">Send next queued email</button></div><p id="admin-status" class="form-status" role="status"></p><div id="applications"></div><section class="section"><div class="eyebrow">SEPARATE FROM PLATFORM MEMBERSHIP</div><h2>Private supplier research</h2><p class="section-intro">Owner-provided listing summaries are research leads—not approved or verified supplier accounts. Names shown here are manager-only and are not sent to the AI.</p><div class="actions"><button class="quiet" id="load-research">Load private research</button><a class="secondary" href="/ai">Open AI workspace ↗</a></div><p id="research-status" class="form-status" role="status"></p><div id="research-records"></div></section></section>
''')
page('access.html','Secure email access', '''
<section class="narrow"><div class="eyebrow">SINGLE-USE / EMAIL ACCESS</div><h1>One secure link.<br><span>Your next step.</span></h1><div class="form-panel"><h2>Continue with your email link</h2><p class="sub">Confirm below to verify your application email or sign in to an approved account. Links expire and can only be used once.</p><button id="consume-link">Continue securely</button><p id="consume-status" class="form-status" role="status"></p><a id="portal-link" class="primary" href="/portal" hidden>Open supplier account ↗</a><p class="sub"><a href="/supplier#sign-in">Request a new link</a></p></div></section>
''')
page('portal.html','Supplier account', '''
<div class="page-top"><div class="eyebrow">APPROVED SUPPLIER / ACCOUNT</div><h1>Welcome to<br><span>your supplier account.</span></h1><p class="intro">Your application has been approved for platform access. Commercial activity remains subject to a separate agreement.</p></div><p id="portal-status" class="form-status" role="status"></p><div id="portal-content" hidden><div class="portal-grid"><section class="form-panel"><div class="panel-title"><h2>Business profile</h2><span class="badge approved">Approved access</span></div><dl id="profile" class="details"></dl></section><section class="form-panel"><h2>Next steps</h2><p class="intro">Discuss your capabilities and relevant sourcing requirements with the STRATEVO team.</p><a class="primary" href="https://app.minup.io/book/stratevo" target="_blank" rel="noopener noreferrer">Arrange a conversation ↗</a><p class="notice">No orders, payments, certification badges or public supplier introductions are created by approval.</p></section></div><div class="actions"><button id="supplier-logout" class="quiet">Sign out</button></div></div>
''')

page('index.html','Sourcing intelligence', (ROOT/'templates'/'ai.content.html').read_text())
